window.addEventListener('keydown', e => {
   e.preventDefault();
   if (e.ctrlKey && e.altKey && e.code == 'ArrowUp') document.querySelector('#KeyW').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'ArrowLeft') document.querySelector('#KeyA').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'ArrowDown') document.querySelector('#KeyS').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'ArrowRight') document.querySelector('#KeyD').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F1') document.querySelector('#Digit1').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F2') document.querySelector('#Digit2').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F3') document.querySelector('#Digit3').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F4') document.querySelector('#Digit4').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F5') document.querySelector('#Digit5').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F6') document.querySelector('#Digit6').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F7') document.querySelector('#Digit7').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F8') document.querySelector('#Digit8').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F9') document.querySelector('#Digit9').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F10') document.querySelector('#Digit0').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F11') document.querySelector('#Minus').classList.add('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F12') document.querySelector('#Equal').classList.add('pressed');
   else document.querySelector(`#${e.code}`).classList.add('pressed');
});
window.addEventListener('keyup', e => {
   e.preventDefault();
   if (e.ctrlKey && e.altKey && e.code == 'ArrowUp') document.querySelector('#KeyW').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'ArrowLeft') document.querySelector('#KeyA').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'ArrowDown') document.querySelector('#KeyS').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'ArrowRight') document.querySelector('#KeyD').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F1') document.querySelector('#Digit1').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F2') document.querySelector('#Digit2').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F3') document.querySelector('#Digit3').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F4') document.querySelector('#Digit4').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F5') document.querySelector('#Digit5').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F6') document.querySelector('#Digit6').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F7') document.querySelector('#Digit7').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F8') document.querySelector('#Digit8').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F9') document.querySelector('#Digit9').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F10') document.querySelector('#Digit0').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F11') document.querySelector('#Minus').classList.remove('pressed');
   else if (e.ctrlKey && e.altKey && e.code == 'F12') document.querySelector('#Equal').classList.remove('pressed');
   else document.querySelector(`#${e.code}`).classList.remove('pressed');
});